name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev mpich

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v1

      - name: Remove Manifest (for cross-version compatibility)
        shell: bash
        run: |
          rm -f Manifest.toml
          rm -f docs/Manifest.toml

      - name: Instantiate package dependencies
        run: |
          julia --project=. --compiled-modules=no -e '
            using Pkg
            Pkg.instantiate()
          '

      - name: Instantiate documentation dependencies
        run: |
          julia --project=docs --compiled-modules=no -e '
            using Pkg
            Pkg.instantiate()
          '

      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs --compiled-modules=no docs/make.jl
